version: '2'
services:
  pteryx:
    build: .
    image: pteryx
    stdin_open: True
    tty: True
    volumes:
      - ./pteryx/workflow:/pteryx/workflow
      - ./tests:/usr/src/pteryx/tests
      - ./tests/fixtures/mesoplasma:/pteryx/inputs
      - .:/usr/src/pteryx
      - /mnt/data2/pteryx_outputs:/usr/src/pteryx/outputs
      - /mnt/data2/dfast_db:/usr/src/pteryx/db
