#!/bin/bash
snakemake -s pteryx.smk \
    --config name=SYN7260 \
             nanopore=input/SYN7260.ont.fq.gz \
             illumina=["input/SYN7260.1.fq.gz","input/SYN7260.2.fq.gz"] \
             size=5M \
             tax=pro \
             outdir=/usr/src/pteryx/output \
             porefilt_correct=False \
             canu_correct=True \
             polish_iterations=1 \
    --dag | dot -Tpng > images/pteryx_dag.png
