#!/bin/bash
# Given an NCBI FTP URL, it downloads the directory.
# Surely this isn't the right way to do this, but w/e i guess

FTP_DIR=$1
ACCESSION_DIR=`echo "$FTP_DIR" | grep -oP  "(GCF_.*)"`
mkdir -p ncbi/${ACCESSION_DIR}
cd ncbi/${ACCESSION_DIR}
parallel wget ${FTP_DIR}/{} ::: `curl ${FTP_DIR}/md5checksums.txt | tr -s ' ' '\t' | cut -f 2`
